# Generated by Django 4.0.5 on 2022-06-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='Brend')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('model', models.CharField(max_length=20, verbose_name='Mahsulot modeli')),
                ('cost', models.PositiveIntegerField(default=100, verbose_name='Narx')),
                ('photo', models.ImageField(blank=True, upload_to='product-photos/', verbose_name='Mahsulot rasmi')),
                ('views', models.IntegerField(default=0)),
                ('like', models.PositiveIntegerField(default=0)),
                ('product_count', models.PositiveIntegerField(default=10, verbose_name='Mahsulot soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Savatcha',
            },
        ),
    ]
